/*
 * generated by Xtext
 */
package tom;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TomModelRuntimeModule extends tom.AbstractTomModelRuntimeModule {

}
