/*
 * generated by Xtext
 */
package tom;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TomModelStandaloneSetup extends TomModelStandaloneSetupGenerated{

	public static void doSetup() {
		new TomModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

