/*
 * generated by Xtext
 */
package tom.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TomModelUiModule extends tom.ui.AbstractTomModelUiModule {
	public TomModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
