<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tom" nsURI="http://www.tom3.tom/tom" nsPrefix="tom">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="HostCode" eSuperTypes="#//Statement #//Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="call" eType="#//TermOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Declaration" eSuperTypes="#//Expression #//LocalVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Affectation" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocs" upperBound="-1"
        eType="#//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context"/>
  <eClassifiers xsi:type="ecore:EClass" name="Linkable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//Linkable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extend" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//Linkable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//Arguments"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Linkable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalVariable" eSuperTypes="#//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariable" eSuperTypes="#//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableSimple" eSuperTypes="#//LocalVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableList" eSuperTypes="#//LocalVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//Context"/>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Block #//Linkable #//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Callback" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" ordered="false"
        upperBound="-1" eType="#//CallbackDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallbackDefinition" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arguments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//Argument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Argument" eSuperTypes="#//VariableSimple"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentTypeSuffix" eSuperTypes="#//Argument"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentTypePrefix" eSuperTypes="#//Argument"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImportConstruct" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncludeConstruct" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ext" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" eSuperTypes="#//Context"/>
  <eClassifiers xsi:type="ecore:EClass" name="Term" eSuperTypes="#//Constraint #//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="TermSum" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Term" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TermConst" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="int" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TermNull" eSuperTypes="#//TermConst"/>
  <eClassifiers xsi:type="ecore:EClass" name="TermVariable" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TermOperation" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terms" ordered="false"
        upperBound="-1" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Return" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" eType="#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchConsctruct" eSuperTypes="#//Statement #//Context"/>
  <eClassifiers xsi:type="ecore:EClass" name="MatchPattern" eSuperTypes="#//MatchConsctruct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//ArgumentMatch"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternActions" upperBound="-1"
        eType="#//PatternAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentMatch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternAction" eSuperTypes="#//Context #//Linkable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" eType="#//PatternList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintPattern" eSuperTypes="#//MatchConsctruct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintActions" upperBound="-1"
        eType="#//ConstraintAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintAction" eSuperTypes="#//Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelOperator">
    <eLiterals name="inf"/>
    <eLiterals name="infeg" value="1"/>
    <eLiterals name="eg" value="2"/>
    <eLiterals name="supeg" value="3"/>
    <eLiterals name="sup" value="4"/>
    <eLiterals name="neg" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedPattern" eSuperTypes="#//Pattern #//LocalVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plainPattern" eType="#//Pattern"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AntiPattern" eSuperTypes="#//Pattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//PlainPatternOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainPatternConst" eSuperTypes="#//Pattern #//RulePattern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="head" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainPatternVariable" eSuperTypes="#//Pattern #//RulePattern #//VariableSimple"/>
  <eClassifiers xsi:type="ecore:EClass" name="JokerPattern" eSuperTypes="#//Pattern #//RulePattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="PlainPatternOperation" eSuperTypes="#//Pattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="heads" eType="#//OperationList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" eType="#//List" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="heads" unique="false" upperBound="-1"
        eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="log" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExplicitTermList" eSuperTypes="#//List">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" upperBound="-1"
        eType="#//Pattern" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainPatternVariableList" eSuperTypes="#//Pattern #//RulePattern #//VariableList"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnyPattern" eSuperTypes="#//Pattern #//RulePattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicitPairList" eSuperTypes="#//List">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" upperBound="-1"
        eType="#//PairPattern" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PairPattern" eSuperTypes="#//Linkable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//Pattern"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StrategyConstruct" eSuperTypes="#//Type #//Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implement" eType="#//TermOperation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//Arguments"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visitlist" upperBound="-1"
        eType="#//StrategyVisit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StrategyVisit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//VisitAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisitAction" eSuperTypes="#//Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//PatternList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" upperBound="-1"
        eType="#//Pattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="#//Constraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintOr" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Constraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintAnd" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Constraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintP" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="#//Constraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintMatch" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintOp" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//RelOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GomConstruct" eSuperTypes="#//Block #//Linkable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="option" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" unique="false"
        upperBound="-1" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" ordered="false"
        upperBound="-1" eType="#//Definition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Definition"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDefinition" eSuperTypes="#//Type #//Definition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="opDefinition" upperBound="-1"
        eType="#//OperatorDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorDefinition" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentsList" eSuperTypes="#//Arguments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HookDefinition" eSuperTypes="#//Definition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hookOperation" eType="#//HookOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HookModuleDefinition" eSuperTypes="#//HookDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hookType" eType="#//GomConstruct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HookTypeDefinition" eSuperTypes="#//HookDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hookType" eType="#//TypeDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HookOperatorDefinition" eSuperTypes="#//HookDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hookType" eType="#//OperatorDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HookOperation" eSuperTypes="#//Linkable"/>
  <eClassifiers xsi:type="ecore:EClass" name="HostHookOperation" eSuperTypes="#//HookOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//Arguments"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" ordered="false"
        upperBound="-1" eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hook_Rules" eSuperTypes="#//HookOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hook_Graphrules" eSuperTypes="#//HookOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphRules" upperBound="-1"
        eType="#//GraphRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hook_Make" eSuperTypes="#//HostHookOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hook_Make_Insert" eSuperTypes="#//HostHookOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hook_Make_Empty" eSuperTypes="#//HostHookOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hook_Free" eSuperTypes="#//HostHookOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hook_FL" eSuperTypes="#//HostHookOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hook_AU" eSuperTypes="#//HostHookOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hook_Interface" eSuperTypes="#//HostHookOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hook_Imports" eSuperTypes="#//HostHookOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hook_Block" eSuperTypes="#//HostHookOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern" eType="#//RulePattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cond" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RulePattern" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedRulePattern" eSuperTypes="#//RulePattern #//LocalVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plainRulePattern" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AntiRulePattern" eSuperTypes="#//RulePattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//RulePattern"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainRulePatternOperation" eSuperTypes="#//RulePattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="heads" eType="#//OperationList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//RulePattern" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="termcond" eType="#//TermGraph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="termGraph" eType="#//TermGraph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cond" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TermGraph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="termGraph" eType="#//PlainTermGraph"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainTermGraph"/>
  <eClassifiers xsi:type="ecore:EClass" name="TermGraphVariable" eSuperTypes="#//PlainTermGraph #//Linkable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TermGraphFunc" eSuperTypes="#//PlainTermGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="head" eType="#//OperationList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terms" upperBound="-1"
        eType="#//TermGraph" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionOr" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Condition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionAnd" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Condition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionP" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionRule" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//Condition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionOp" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Condition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//RelOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLTerm" eSuperTypes="#//Pattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="XMLTermSimple" eSuperTypes="#//XMLTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nameList" eType="#//XMLNameList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrList" eType="#//XMLAttrList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLTermDouble" eSuperTypes="#//XMLTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nameList" eType="#//XMLNameList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrList" eType="#//XMLAttrList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childs" eType="#//XMLChilds"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" eType="#//XMLNameList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLTermText" eSuperTypes="#//XMLTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLTermComment" eSuperTypes="#//XMLTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLTermProcess" eSuperTypes="#//XMLTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLNameList">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="XMLName" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="XMLAttrList"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLAttrList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrs" upperBound="-1"
        eType="#//XMLAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="XMLAttribute1" eSuperTypes="#//XMLAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLAttribute2" eSuperTypes="#//XMLAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLAttribute3" eSuperTypes="#//XMLAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="XMLChilds"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLChilds">
    <eStructuralFeatures xsi:type="ecore:EReference" name="terms" upperBound="-1"
        eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeTerm" eSuperTypes="#//Block #//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="#//KeyWord"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyWord" eSuperTypes="#//Linkable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//Arguments"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operator" eSuperTypes="#//Block #//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="#//KeyWord"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorList" eSuperTypes="#//Block #//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="#//KeyWord"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorArray" eSuperTypes="#//Block #//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="#//KeyWord"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation" eSuperTypes="#//Block #//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileFrom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementaryTranformations"
        upperBound="-1" eType="#//ElementaryTransformation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementaryTransformation" eSuperTypes="#//Operation #//Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implement" eType="#//TermOperation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementaryTransformationRules"
        upperBound="-1" eType="#//ElementaryTransformationRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementaryTransformationRule" eSuperTypes="#//Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//Pattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tracelink" eSuperTypes="#//GlobalVariable #//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resolve" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Tracelink"/>
  </eClassifiers>
</ecore:EPackage>
