/*
 * generated by Xtext
 */
package t3.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.contentassist.ITemplateProposalProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class T3UiModule extends t3.ui.AbstractT3UiModule {
	public T3UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends ITemplateProposalProvider> bindITemplateProposalProvider() {
		return tom.ui.contentassist.TomTemplateProvider.class;
	}
}
