/*
 * generated by Xtext
 */
package tom3.ui.contentassist

import tom3.ui.contentassist.AbstractTomProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TomProposalProvider extends AbstractTomProposalProvider {
}
