/*
 * generated by Xtext
 */
package tom3.validation

//import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TomValidator extends tom.validation.Tom3Validator {

}
