/*
 * generated by Xtext
 */
package t3;

import org.eclipse.xtext.scoping.IGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class T3RuntimeModule extends t3.AbstractT3RuntimeModule {

	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return tom.scoping.Tom3ImportScopeProvider.class;
	}
}
