/*
 * generated by Xtext
 */
package t3;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

import tom.TomPackage;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class T3StandaloneSetup extends T3StandaloneSetupGenerated{

	public static void doSetup() {
		new T3StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
    public void register(Injector injector) {
        if (!EPackage.Registry.INSTANCE.containsKey("http://www.tom3.tom/tom")) {
            EPackage.Registry.INSTANCE.put("http://www.tom3.tom/tom", TomPackage.eINSTANCE);
        }
        super.register(injector);
    }
}

