/*
 * generated by Xtext
 */
package tom.ui.contentassist

import tom.ui.contentassist.AbstractTomModelProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TomModelProposalProvider extends AbstractTomModelProposalProvider {
}
