/*
 * generated by Xtext
 */
package tom3;

import org.eclipse.xtext.scoping.IGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TomRuntimeModule extends tom3.AbstractTomRuntimeModule {

	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return tom.scoping.Tom3ImportScopeProvider.class;
	}
}
