/*
 * generated by Xtext
 */
package tom3;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TomStandaloneSetup extends TomStandaloneSetupGenerated{

	public static void doSetup() {
		new TomStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

