/*
 * generated by Xtext
 */
package tom3.scoping

import tom.scoping.TomModelScopeProvider

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 *
 */
class TomScopeProvider extends TomModelScopeProvider {

}
