/*
 * generated by Xtext
 */
package t3.ui.contentassist

import t3.ui.contentassist.AbstractT3ProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class T3ProposalProvider extends AbstractT3ProposalProvider {
}
